### ISSUE TITLE
When is add cure cosmo?

### ISSUE THREAD

**Issue by Ricotan-naboon** [greymd/cureutils#25]
1.2.0を使用中です。キュアコスモが追加されるのを全裸で待機していますが追加予定はございますでしょうか。既にシェル芸Botでは追加されているのですが....

**Comment by greymd** [comment]
@Ricotan-naboon  rubicure 側をアップデートすれば反映されますよー。

```
gem update rubicure
```

**Comment by Ricotan-naboon** [comment]
了解です、やってみます。
回答ありがとうございました。
